### ISSUE TITLE
Image rendering issues for "icons"

### ISSUE THREAD

**Issue by allanday** [FedoraQt/MediaWriter#231]
Screenshot from Fedora 31:

![image](https://user-images.githubusercontent.com/213068/78242346-bfa1d200-74d9-11ea-855a-ca9643ee91bf.png)

Is it just the outline of the circle that has ragged edges, or is the image as a whole being incorrectly rendered?

cc @jimmac

**Comment by jimmac** [comment]
Looks like a scaling artifact, the source images are larger RGBA PNGs and have no jaggies.

**Comment by MartinBriza** [comment]
I see you've reported multiple issues for FMW today. Can you please specify
which version you tested and how have you obtained so it makes debugging
easier for me? Thanks

All of these issues (maybe except border radius for buttons) are probably
related to how high DPI scaling works in Qt for Windows. That being said,
have you tested the app on other platforms?

**Comment by allanday** [comment]
I was testing 4.1.3, installed as a Flatpak from Flathub, on F31. I've also obviously tried it on Windows 10 recently, with whatever download is currently being offered (4.1.4 from the looks of things).

4.1.4-4 (installed on F32 from a package) appears to show the same issues I've reported recently.

**Comment by MartinBriza** [comment]
I released 4.1.5 4 days ago and I doubt it's available from getfedora.org yet (especially since I haven't really let Release Engineering know it's out because I feel like I should make more changes to the project before doing an official release for Fedora). However, please, for future bugs, use the version that's distributed through this page. The difference between 4.1.5 and 4.1.3 is almost one year and I'm not sure which Qt version is the one on getfedora compiled against but some of the highDPI related glitches you're seeing are definitely related to what Qt does and with every other version they claim they "fixed the issues with highDPI".

I'm going to push 4.1.5 to Flathub (probably just the beta channel) so it's easier for you to test it if you're planning to do so again soon.

Then again, I'm definitely going to test the app on all platforms more myself in near future so issues like this are solved for the next version I'm going to announce to Fedora Release Engineering.

**Comment by grulja** [comment]
It's a scaling issue, I tried to improve it by including same images in lower resolution (closer to the size used in FMW), but it's still not perfect. I will look into this further.

**Comment by grulja** [comment]
The new UI of upcoming FMW doesn't use these images so this will no longer be an issue.
