### ISSUE TITLE
Mediawriter F33 4.2.0-1 FC33 freezes custom install

### ISSUE THREAD

**Issue by coz** [FedoraQt/MediaWriter#277]
F33 mediawriter freezes when trying to create a "custom: iso.
It will not open a directory to choose the iso from, or, it will open the file manager but that also is non responsive.
This is a fresh install of F33 MATE-COMPIZ.
Terminal readout;

[coz@localhost ~]$ mediawriter
W@183ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/iso/Fedora-Server-netinst-armhfp-33-1.2.iso" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/images/Fedora-Server-33-1.2.armhfp.raw.xz"
W@183ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/images/Fedora-Server-33-1.2.armhfp.raw.xz" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/images/Fedora-Server-armhfp-33-1.2-sda.raw.xz"
W@183ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Silverblue/x86_64/iso/Fedora-Silverblue-ostree-x86_64-33-1.2.iso" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-33-1.2.iso"
W@184ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Workstation/armhfp/images/Fedora-Workstation-33-1.2.armhfp.raw.xz" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Workstation/armhfp/images/Fedora-Workstation-armhfp-33-1.2-sda.raw.xz"
W@184ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-33-1.2.iso" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-33-1.2.x86_64.vagrant-libvirt.box"
W@184ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-33-1.2.x86_64.vagrant-libvirt.box" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-33-1.2.x86_64.vagrant-virtualbox.box"
W@184ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/iso/Fedora-Scientific_KDE-Live-x86_64-33-1.2.iso" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Scientific-Vagrant-33-1.2.x86_64.vagrant-libvirt.box"
W@184ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Scientific-Vagrant-33-1.2.x86_64.vagrant-libvirt.box" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Scientific-Vagrant-33-1.2.x86_64.vagrant-virtualbox.box"
W@185ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Server/armhfp/images/Fedora-Server-armhfp-32-1.6-sda.raw.xz" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Server/armhfp/iso/Fedora-Server-netinst-armhfp-32-1.6.iso"
W@185ms: SHA256 hash of "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Server/armhfp/iso/Fedora-Server-netinst-armhfp-32-1.6.iso" changed from "fff20ec4f6ce3ea232c74b80b7ffad935bfe213652aad669dedfabb54e98cefc" to "888ae8108f89b6f6e73815120f8e812daabaaf4479e3022ca40591f399eaad58"
W@186ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Silverblue/x86_64/iso/Fedora-Silverblue-ostree-x86_64-32-1.6.iso" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-32-1.6.iso"
W@186ms: SHA256 hash of "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-32-1.6.iso" changed from "a241b624af5218cd8dc9b8459a34b6682d813fd6305ceab3d95e1f4da9803d7d" to "4d0f6653e2e0860c99ffe0ef274a46d875fb85bd2a40cb896dce1ed013566924"
W@186ms: Url "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-libvirt.box" changed to "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-virtualbox.box"
W@186ms: SHA256 hash of "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-virtualbox.box" changed from "b18475f18de00bb3fd7d8300b755fa541e7521e34cc8be18592c5ef854520a96" to "01d0f81c361ab93dbafd9f64e2a08afbc739f5b4bf509529943b309244d95823"
W@186ms: Url "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-virtualbox.box" changed to "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-32-1.6.iso"
W@186ms: SHA256 hash of "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-32-1.6.iso" changed from "01d0f81c361ab93dbafd9f64e2a08afbc739f5b4bf509529943b309244d95823" to "d00ee0bd73d260eb7769d12a636cca86c54e486bf7335192a88ddd574ebaa51d"
W@901ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/images/Fedora-Server-armhfp-33-1.2-sda.raw.xz" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/iso/Fedora-Server-netinst-armhfp-33-1.2.iso"
W@901ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/iso/Fedora-Server-netinst-armhfp-33-1.2.iso" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/images/Fedora-Server-33-1.2.armhfp.raw.xz"
W@901ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/images/Fedora-Server-33-1.2.armhfp.raw.xz" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Server/armhfp/images/Fedora-Server-armhfp-33-1.2-sda.raw.xz"
W@904ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Workstation/armhfp/images/Fedora-Workstation-armhfp-33-1.2-sda.raw.xz" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Workstation/armhfp/images/Fedora-Workstation-33-1.2.armhfp.raw.xz"
W@904ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Workstation/armhfp/images/Fedora-Workstation-33-1.2.armhfp.raw.xz" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Workstation/armhfp/images/Fedora-Workstation-armhfp-33-1.2-sda.raw.xz"
W@905ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-33-1.2.x86_64.vagrant-virtualbox.box" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-33-1.2.iso"
W@905ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Scientific-Vagrant-33-1.2.x86_64.vagrant-virtualbox.box" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/iso/Fedora-Scientific_KDE-Live-x86_64-33-1.2.iso"
W@905ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-33-1.2.iso" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-33-1.2.x86_64.vagrant-libvirt.box"
W@905ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-33-1.2.x86_64.vagrant-libvirt.box" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-33-1.2.x86_64.vagrant-virtualbox.box"
W@905ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/iso/Fedora-Scientific_KDE-Live-x86_64-33-1.2.iso" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Scientific-Vagrant-33-1.2.x86_64.vagrant-libvirt.box"
W@906ms: Url "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Scientific-Vagrant-33-1.2.x86_64.vagrant-libvirt.box" changed to "https://download.fedoraproject.org/pub/alt/releases/33/Labs/x86_64/images/Fedora-Scientific-Vagrant-33-1.2.x86_64.vagrant-virtualbox.box"
W@906ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Server/armhfp/iso/Fedora-Server-netinst-armhfp-32-1.6.iso" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Server/armhfp/images/Fedora-Server-armhfp-32-1.6-sda.raw.xz"
W@906ms: SHA256 hash of "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Server/armhfp/images/Fedora-Server-armhfp-32-1.6-sda.raw.xz" changed from "888ae8108f89b6f6e73815120f8e812daabaaf4479e3022ca40591f399eaad58" to "fff20ec4f6ce3ea232c74b80b7ffad935bfe213652aad669dedfabb54e98cefc"
W@906ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Server/armhfp/images/Fedora-Server-armhfp-32-1.6-sda.raw.xz" changed to "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Server/armhfp/iso/Fedora-Server-netinst-armhfp-32-1.6.iso"
W@906ms: SHA256 hash of "https://download.fedoraproject.org/pub/fedora/linux/releases/32/Server/armhfp/iso/Fedora-Server-netinst-armhfp-32-1.6.iso" changed from "fff20ec4f6ce3ea232c74b80b7ffad935bfe213652aad669dedfabb54e98cefc" to "888ae8108f89b6f6e73815120f8e812daabaaf4479e3022ca40591f399eaad58"
W@908ms: Url "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-32-1.6.iso" changed to "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-libvirt.box"
W@908ms: SHA256 hash of "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-libvirt.box" changed from "d00ee0bd73d260eb7769d12a636cca86c54e486bf7335192a88ddd574ebaa51d" to "b18475f18de00bb3fd7d8300b755fa541e7521e34cc8be18592c5ef854520a96"
W@908ms: Url "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-libvirt.box" changed to "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-virtualbox.box"
W@908ms: SHA256 hash of "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-virtualbox.box" changed from "b18475f18de00bb3fd7d8300b755fa541e7521e34cc8be18592c5ef854520a96" to "01d0f81c361ab93dbafd9f64e2a08afbc739f5b4bf509529943b309244d95823"
W@908ms: Url "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/images/Fedora-Python-Classroom-Vagrant-32-1.6.x86_64.vagrant-virtualbox.box" changed to "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-32-1.6.iso"
W@908ms: SHA256 hash of "https://download.fedoraproject.org/pub/alt/releases/32/Labs/x86_64/iso/Fedora-Python-Classroom-Live-x86_64-32-1.6.iso" changed from "01d0f81c361ab93dbafd9f64e2a08afbc739f5b4bf509529943b309244d95823" to "d00ee0bd73d260eb7769d12a636cca86c54e486bf7335192a88ddd574ebaa51d"

**Comment by grulja** [comment]
I cannot reproduce on GNOME or KDE.

**Comment by meesha7** [comment]
I have the same issue with `4.2.0-1.fc33` on Cinnamon. Sometimes when I run the program from terminal it opens the file dialog, but nothing is clickable. But mostly the file dialog doesn't open at all.

**Comment by grulja** [comment]
Do you have `QGnomePlatform` installed? Can you try uninstall it and try it?

**Comment by grulja** [comment]
It looks like a Qt issue https://bugreports.qt.io/browse/QTBUG-59184. I cannot reproduce it in Fedora Workstation, because there it is workarounded by using QGnomePlatform.

**Comment by grulja** [comment]
This is not a bug in FMW.

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/MediaWriter/pull/342.

**Comment by dreua** [comment]
Unfortunately I'm still seeing this issue on F34 with the RPM (mediawriter-4.2.2-2.fc34) :cry:

**Comment by grulja** [comment]
> Unfortunately I'm still seeing this issue on F34 with the RPM (mediawriter-4.2.2-2.fc34) 
> 
> Workaround (hard to find and not ideal): `sudo mediawriter` - works but the file chooser looks ugly

What desktop environment do you use (GNOME or KDE or something else)? Do you have `xdg-desktop-portal `and one of x`dg-desktop-portal-[kde|gtk]` installed?

**Comment by dreua** [comment]
Using Gnome on X11. Can't check the packages right now, will update this post later.
