### ISSUE TITLE
Unable to download an image from a custom URL

### ISSUE THREAD

**Issue by kparal** [FedoraQt/MediaWriter#460]
I wanted to test FMW download feature more quickly, and so I wanted to download from my localhost instead of the internet. I downloaded [releases.json](http://getfedora.org/releases.json) and added:
```
{"link": "http://127.0.0.1:8000/Fedora-Workstation-Live-x86_64-36-1.5.iso", "subvariant": "Workstation", "version": "36", "arch": "x86_64", "variant": "Workstation", "sha256": "80169891cb10c679cdc31dc035dab9aae3e874395adc5229f0fe5cfcc111cc8c", "size": "2018148352"},
```
But turns out this doesn't work, the image download is immediately marked as failed. In the log I see:
```
W@13163ms: Error QNetworkReply::ContentNotFoundError reading from QUrl("http://ftp.fi.muni.cz/pub/linux/centos-stream/Fedora-Workstation-Live-x86_64-36-1.5.iso") : "Error transferring http://ftp.fi.muni.cz/pub/linux/centos-stream/Fedora-Workstation-Live-x86_64-36-1.5.iso - server replied: Not Found"
W@13167ms: Computed SHA256 hash of "/home/kparal/Downloads/Fedora-Workstation-Live-x86_64-36-1.5.iso.part"  -  "d13fb7e20ee361598d306336c5d9dbfb260ab7e8e2d85166b16097dd9d4ea9a7" does not match expected "80169891cb10c679cdc31dc035dab9aae3e874395adc5229f0fe5cfcc111cc8c"
```
So it seems that FMW is always trying to download the image from mirrors, even if it is a direct URL that it should use verbatim.

My `releases.json`:
[releases.json.zip](https://github.com/FedoraQt/MediaWriter/files/8638963/releases.json.zip)

Full FMW log:
[fmw-log.txt](https://github.com/FedoraQt/MediaWriter/files/8638968/fmw-log.txt)

```
mediawriter-4.9.99-2.fc36.x86_64
```

**Comment by grulja** [comment]
Maybe a similar issue to https://github.com/FedoraQt/MediaWriter/issues/264?

**Comment by ferdnyc** [comment]
I think this may have been addressed as a side-effect of 57e43cd.

## The original issue
AFAICT, the problem wasn't that FMW was trying to download from a mirror.<sup>1</sup> (That failed, anyway; the log shows this at the end: `W@13163ms: Error QNetworkReply::ContentNotFoundError reading from QUrl("http://ftp.fi.muni.cz/pub/linux/centos-stream/Fedora-Workstation-Live-x86_64-36-1.5.iso") : "Error transferring http://ftp.fi.muni.cz/pub/linux/centos-stream/Fedora-Workstation-Live-x86_64-36-1.5.iso - server replied: Not Found`)

The problem was that when the custom `releases.json` was read in, _baaaad_ things happened. The shared logs are full of warnings about data being changed in nonsense ways.

## The current code
That doesn't happen anymore, tho. I tested a custom `releases.json` set up exactly the same way, with my local image inserted at the top of the file, and instead of those warnings all I saw in the debug output was:

### Loading the compiled-in file
```text
D@122ms: ReleaseManager construction
D@122ms: ReleaseManager Received a metadata json
D@124ms: ReleaseManager Adding "cosmic-atomic" "42" "aarch64"
D@125ms: ReleaseManager Adding "cosmic-atomic" "42" "x86_64"
D@132ms: ReleaseManager Adding "kde" "42" "aarch64"
D@132ms: ReleaseManager Adding "kde" "42" "ppc64le"
[...]
```

### Then, loading my modified file
```text
D@387ms: Download Trying to download from a mirror: QUrl("file:///tmp/new-releases.json")
W@427ms: Failed to register with host portal QDBusError("org.freedesktop.portal.Error.Failed", "Could not register app ID: Connection already associated with an application ID")
D@427ms: Download Finished successfully
D@427ms: ReleaseManager Received a metadata json
D@428ms: ReleaseManager Adding "server" "44" "x86_64"
D@428ms: ReleaseManager Adding "cosmic-atomic" "42" "aarch64"
D@429ms: ReleaseManager Adding "cosmic-atomic" "42" "x86_64"
D@436ms: ReleaseManager Adding "kde" "42" "aarch64"
D@436ms: ReleaseManager Adding "kde" "42" "ppc64le"
```

`"server" "44" "x86_64"` was my new, local addition.

## The (presumed) fix
The changes in 57e43cd include this, in the commit message:

> With Fedora Onyx not being available yet, it takes a position in the model and because of that it is filtered out, however, this breaks index mapping since we were using position of items in the combobox.

### Original attempt, continued
That same issue (index mapping getting broken when the model changes) would presumably have affected a model if, say, a new release was inserted at the top of the list on a subsequent reload.

And based on the warnings in @kparal's logs, that's exactly what happened. The custom `release.json` file was loaded in, and all of the existing releases had their data _scrambled_ because all of the indices changed.

That's why the log showed a TON of these kind of messages:
`W@191ms: Url "https://download.fedoraproject.org/pub/fedora/linux/releases/test/36_Beta/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-36_Beta-1.4.iso" changed to "http://127.0.0.1:8000/Fedora-Workstation-Live-x86_64-36-1.5.iso"`
`W@191ms: SHA256 hash of "http://127.0.0.1:8000/Fedora-Workstation-Live-x86_64-36-1.5.iso" changed from "6eaa4097a5788e800b307f9d92544e4c2c78f824d91ddbbbb769947ece5a3c85" to "80169891cb10c679cdc31dc035dab9aae3e874395adc5229f0fe5cfcc111cc8c"`

And why the end of the log shows a hash check failure:
`W@13167ms: Computed SHA256 hash of "/home/kparal/Downloads/Fedora-Workstation-Live-x86_64-36-1.5.iso.part"  -  "d13fb7e20ee361598d306336c5d9dbfb260ab7e8e2d85166b16097dd9d4ea9a7" does not match expected "80169891cb10c679cdc31dc035dab9aae3e874395adc5229f0fe5cfcc111cc8c"`

`80169891...` is the _correct_ hash value for the local file, according to @kparal's `release.json` file. `6eaa4097...` is the _correct_ hash for `https://download.fedoraproject.org/pub/fedora/linux/releases/test/36_Beta/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-36_Beta-1.4.iso`, according to the custom `releases.json` supplied.

Somewhere along the way, the Qt model for releases got scrambled enough that it was trying to download a beta image instead of the release provided, from the the wrong URL, with the wrong hash expected for the resulting file.

## Conclusion
My testing shows that doesn't happen anymore, I believe thanks to 57e43cd (and possibly other changes). I used a file served from my local  `http://127.0.0.1/~ferd/` space (stored locally in `$HOME/public_html/`), and FMW retrieved and verified it with no issues (except the mirror attempts<sup>1</sup>).

Short story very (very) long, AFAICT this is now fixed.

## Notes
1. FMW _will_ always try to get a mirrorlist, even when it's not necessary because the original URL is perfectly accessible. But that's a separate issue, and didn't affect this. But it doesn't seem mirror lookups are being reserved for _just_ failure recovery.
   
   In fact, if a custom URL is used, at the start of downloading FMW will immediately request a mirrorlist using the full server path of the original URL. That may not have affected @kparal who was using `http://127.0.0.1:8000/Fedora-Workstation-Live-x86_64-36-1.5.iso` as the custom URL, but I tested with `http://localhost/~ferd/download/Fedora-Server-dvd-x86_64-44-1.7.iso`, and FMW made mirrorlist requests for `https://mirrors.fedoraproject.org/mirrorlist?path=/~ferd/download/Fedora-Server-dvd-x86_64-44-1.7.iso` which were obviously never going to work. (Those requests were unnecessary anyway, since the download from my local Apache server proceeded fine.)

**Comment by kparal** [comment]
No, it's still broken, ferdnyc's AI is wrong. But it helped me better identify the problem.

> In fact, if a custom URL is used, at the start of downloading FMW will immediately request a mirrorlist using the full server path of the original URL.

This is the first part of the problem. Even for a custom URL, it always contacts the mirrors. The mirrors are unlikely to have this file (unless you use the same path as the official path), and even if they had it, it might be a different file (if you want to serve some nightly image, etc). I don't know whether after all the mirrors are tried the original URL (the custom URL) is tried. There's a second problem that breaks the download process.

The second problem is that when (certain) mirrors return 404, FMW saves that response as `*.iso.part` file in `~/Downloads`. The error response is assumed to be the ISO download. Once it is saved, it verifies that file and obviously its checksum doesn't match the desired checksum (of the true ISO). And the whole download process is marked as failed.

In my today's attempt, I downloaded some Rawhide nightly image. I renamed it to `Fedora-Workstation-Live-45-1.1.x86_64.iso` (because there's a [name filtering minefield](https://github.com/FedoraQt/MediaWriter/blob/main/src/app/releasemanager.cpp#L284) when using not well known image names), and added this at the top of `releases.json`:
```
{"link": "http://127.0.0.1:8000/Fedora-Workstation-Live-45-1.1.x86_64.iso", "subvariant": "Workstation", "version": "45", "arch": "x86_64", "variant": "Workstation", "sha256": "de398706d86989cb06345314645880e79c5b2e298ae1b3488ba8ab05e5997d76", "size": "1289193472"},
```
In the log, I see:
```
D@198ms: ReleaseManager Adding "workstation" "45" "x86_64"
D@6585ms: DownloadManager Going to download QUrl("http://127.0.0.1:8000/Fedora-Workstation-Live-45-1.1.x86_64.iso")
D@6609ms: Download Trying to download from a mirror: QUrl("https://mirrors.fedoraproject.org/mirrorlist?path=/Fedora-Workstation-Live-45-1.1.x86_64.iso")
D@6858ms: Download Trying to download from a mirror: QUrl("https://download.cf.centos.org/Fedora-Workstation-Live-45-1.1.x86_64.iso")
W@7525ms: Error QNetworkReply::ContentNotFoundError reading from QUrl("https://download.cf.centos.org/Fedora-Workstation-Live-45-1.1.x86_64.iso") : "Error transferring https://download.cf.centos.org/Fedora-Workstation-Live-45-1.1.x86_64.iso - server replied with status code 404"
D@7525ms: Download Trying to download from a mirror: QUrl("http://mirror.stream.centos.org/Fedora-Workstation-Live-45-1.1.x86_64.iso")
W@7526ms: Computed SHA256 hash of "/home/kparal/Downloads/Fedora-Workstation-Live-45-1.1.x86_64.iso.part"  -  "8bf14e5f86f1e50c130d831e9b9db3061873ec68d826432c3f1f0d99e7833f41" does not match expected "de398706d86989cb06345314645880e79c5b2e298ae1b3488ba8ab05e5997d76"
```
So yes, we go through mirrors first. https://mirrors.fedoraproject.org/mirrorlist?path=/Fedora-Workstation-Live-45-1.1.x86_64.iso responds:
```
# path = Fedora-Workstation-Live-45-1.1.x86_64.iso country = global 
https://download.cf.centos.org/Fedora-Workstation-Live-45-1.1.x86_64.iso
http://mirror.stream.centos.org/Fedora-Workstation-Live-45-1.1.x86_64.iso
```
https://download.cf.centos.org/Fedora-Workstation-Live-45-1.1.x86_64.iso is considered HTTP 404 , which seems fine.
But http://mirror.stream.centos.org/Fedora-Workstation-Live-45-1.1.x86_64.iso seems to not be understood as HTTP 404, even though when I use wget, I get HTTP 301 to https://mirror.stream.centos.org/Fedora-Workstation-Live-45-1.1.x86_64.iso and then HTTP 404.
But FMW downloads the response instead, I see:
```
$ cat ~/Downloads/Fedora-Workstation-Live-45-1.1.x86_64.iso.part 
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>Fedora-Workstation-Live-45-1.1.x86_64.iso</Key><RequestId>FPV3HJG9PD0HAWS5</RequestId><HostId>9lujAK8+G5pSnU9ZkTqSHWNwBuoojV8miiuRavTZIflZijNVP5N0xOM3K16fIhH+TktH8aGY3Ek=</HostId></Error>
```
And then this file is marked as failing checksum, therefore failing the whole download.

I think this is a **genuine bug** that should get fixed (some mirror responses are saved instead of understood as error, maybe the redirect confuses FMW).

As for "**let's make this useful for testing and debugging**", maybe a completely different approach could be used. Ideas:
* When `--releasesUrl` is used, don't go through the mirrors, download directly.
-or-
* Support an envvar that will override any attempted download URL. For example `FMW_FORCE_DOWNLOAD_URL="http://...iso" mediawriter` would use that single URL for anything the user picks.

**Comment by ferdnyc** [comment]
> No, it's still broken, ferdnyc's AI is wrong.

For the record, I wrote every word of my comment myself. There was no AI involvement whatsoever.

(I'm perfectly capable of being wrong on my own, I've never needed any help with that.)

**Comment by ferdnyc** [comment]
> So yes, we go through mirrors first. https://mirrors.fedoraproject.org/mirrorlist?path=/Fedora-Workstation-Live-45-1.1.x86_64.iso responds:
> 
> 
> ```
> # path = Fedora-Workstation-Live-45-1.1.x86_64.iso country = global 
> https://download.cf.centos.org/Fedora-Workstation-Live-45-1.1.x86_64.iso
> http://mirror.stream.centos.org/Fedora-Workstation-Live-45-1.1.x86_64.iso
> ```


Ah, OK. Because of the local path I used, the mirrorlist request for my file (which was https://mirrors.fedoraproject.org/mirrorlist?path=/~ferd/download/Fedora-Server-dvd-x86_64-44-1.7.iso) came back as just:

```text
error: invalid path
```

...with no URLs to try. That may explain why I seemed to get different results.

**Comment by kparal** [comment]
> For the record, I wrote every word of my comment myself. There was no AI involvement whatsoever.

Sorry! The modern age makes people automatically assume that a long structured detailed text must've been generated. I'll try not to assume next time.

> Ah, OK. Because of the local path I used, the mirrorlist request for my file (which was https://mirrors.fedoraproject.org/mirrorlist?path=/~ferd/download/Fedora-Server-dvd-x86_64-44-1.7.iso) came back as just:

That makes sense. In that case, there was no mirror error, no download of an error message, and the process most likely continued with a direct download from the given URL.

That could also be the workaround - give it a path including some subdir, so that the mirrorlist server will return no mirrors to try.

Because this still returns mirrors: https://mirrors.fedoraproject.org/mirrorlist?path=some.iso
```
# path = some.iso country = global 
https://download.cf.centos.org/some.iso
http://mirror.stream.centos.org/some.iso
```
But this doesn't: https://mirrors.fedoraproject.org/mirrorlist?path=/path/some.iso
```
error: invalid path
```

However, when I try it, it still doesn't work for me. I added this to `releases.json` (notice the `/iso/` subdir):
```
{"link": "http://127.0.0.1:8000/iso/Fedora-Workstation-Live-Rawhide-20260722.n.0.x86_64.iso", "subvariant": "Workstation", "version": "45", "arch": "x86_64", "variant": "Workstation", "sha256": "b0ca751095c6c7181c48ad43d1c29cee47ce3b2e99f575a492ab5b7a35a9fefd", "size": "2955077632"},
```
and I get this:
```
D@5789ms: DownloadManager Going to download QUrl("http://127.0.0.1:8000/iso/Fedora-Workstation-Live-Rawhide-20260722.n.0.x86_64.iso")
D@5813ms: Download Trying to download from a mirror: QUrl("https://mirrors.fedoraproject.org/mirrorlist?path=/iso/Fedora-Workstation-Live-Rawhide-20260722.n.0.x86_64.iso")
D@5817ms: Download Creating a new empty file
W@5937ms: Error QNetworkReply::ContentNotFoundError reading from QUrl("https://mirrors.fedoraproject.org/mirrorlist?path=/iso/Fedora-Workstation-Live-Rawhide-20260722.n.0.x86_64.iso") : "Error transferring https://mirrors.fedoraproject.org/mirrorlist?path=/iso/Fedora-Workstation-Live-Rawhide-20260722.n.0.x86_64.iso - server replied with status code 404"
D@5937ms: Download An error occurred at the end: "Error transferring https://mirrors.fedoraproject.org/mirrorlist?path=/iso/Fedora-Workstation-Live-Rawhide-20260722.n.0.x86_64.iso - server replied with status code 404"
D@8840ms: Drive Helper command: "/usr/libexec/mediawriter/helper" QList("write", "/home/kparal/Downloads/Fedora-Workstation-Live-Rawhide-20260722.n.0.x86_64.iso.part", "/org/freedesktop/UDisks2/block_devices/sda")
W@20944ms: QIODevice::read (QSslSocket): device not open
```
The mirrors are tried and nothing is found, but a 0-byte `Fedora-Workstation-Live-Rawhide-20260722.n.0.x86_64.iso.part` is still created in `~/Downloads`. FMW shows "Downloading" forever (no progress, always 0%), and I have to cancel it.

I'm not actually desperate to find a workaround, so we don't need to dig into this deeper. But the mirror problem should get fixed, and I would be happy if this QA use case got implemented somehow properly in the future.
