### ISSUE TITLE
Publish to Windows Package Managar (WinGet)

### ISSUE THREAD

**Issue by vedantmgoyal9** [FedoraQt/MediaWriter#551]
With every new release of MediaWriter, use a GitHub workflow to update manifests at https://github.com/microsoft/winget-pkgs repository.

I can create a pull request if you would like. It would help in keeping manifests up-to-date at WinGet with every new release automatically.

cc @grulja

**Comment by vedantmgoyal2009** [comment]
Existing projcts which use the action: https://github.com/search?q=vedantmgoyal2009%2Fwinget-releaser+path%3A.github%2Fworkflows%2F+language%3AYAML&type=Code&s=indexed&o=desc

**Comment by grulja** [comment]
> I can create a pull request if you would like. It would help in keeping manifests up-to-date at WinGet with every new release automatically.
> 
Yes, please. I don't have time myself to work on this so if you prepare that change it will be appreciated. Thank you.

**Comment by grulja** [comment]
Hi, it looks this is still not working. See https://github.com/FedoraQt/MediaWriter/runs/8010970301.

**Comment by vedantmgoyal2009** [comment]
Sorry for the inconvenience caused. I've found the issue and it will be fixed by the end of this month.

**Comment by grulja** [comment]
> Sorry for the inconvenience caused. I've found the issue and it will be fixed by the end of this month.

No problem at all. I was just letting you know, not complaining.

**Comment by vedantmgoyal2009** [comment]
Hi, sorry for the delay. Can you please convert the latest release to draft and publish it again?

![image](https://user-images.githubusercontent.com/83997633/188262590-a366fade-e88c-438c-a10b-08aa5ef3335c.png)

And then,

![image](https://user-images.githubusercontent.com/83997633/188262613-adcaee33-68cc-49aa-88d4-5378098ec1e3.png)

**Comment by grulja** [comment]
> Hi, sorry for the delay. Can you please convert the latest release to draft and publish it again?
> 
> ![image](https://user-images.githubusercontent.com/83997633/188262590-a366fade-e88c-438c-a10b-08aa5ef3335c.png)
> 
> And then,
> 
> ![image](https://user-images.githubusercontent.com/83997633/188262613-adcaee33-68cc-49aa-88d4-5378098ec1e3.png)

I don't see such option. Can I just delete it and create again?

**Comment by vedantmgoyal2009** [comment]
@grulja Sure, you can.

**Comment by vedantmgoyal2009** [comment]
BTW, the option should be available at https://github.com/FedoraQt/MediaWriter/releases/tag/5.0.3 for converting the release to draft, if you've maintainer permissions on the repository.

**Comment by grulja** [comment]
I believe I should have all the permissions since I can create releases. I had to delete it and create again.

The job still fails: https://github.com/FedoraQt/MediaWriter/actions/runs/3080349346/jobs/4977582802

Sorry for the delay, I was off for two weeks.

**Comment by vedantmgoyal2009** [comment]
* https://github.com/FedoraQt/MediaWriter/pull/558 should fix the error.

**Comment by grulja** [comment]
FYI: it is still failing.

**Comment by vedantmgoyal2009** [comment]
I don't know why GitHub Actions is still using old workflow file for running the workflow. The error is already fixed.

**Comment by Conan-Kudo** [comment]
It will not use the new workflow until a release is tagged containing it.

**Comment by grulja** [comment]
This is still not working. Currently it seems to fail on invalid github key.

**Comment by vedantmgoyal9** [comment]
Hello @grulja, the GitHub token seems to be expired. You need to regenerate token at https://github.com/settings/tokens and then update the secret at https://github.com/FedoraQt/MediaWriter/settings/secrets/actions.

**Comment by grulja** [comment]
Now it fails with:
```
Error: 
   0: grulja does not have the correct permissions to execute `CreateRef`
```

**Comment by vedantmgoyal9** [comment]
I think that is because the fork (https://github.com/FedoraQt/winget-pkgs) is too old, and the action can't update it through API. Can you please try manually updating it and then try again? Sorry, this is taking so long to work 😢

**Comment by grulja** [comment]
\o/ finally: https://github.com/microsoft/winget-pkgs/pull/195636

**Comment by grulja** [comment]
Hi, it looks

**Comment by vedantmgoyal9** [comment]
Please add `workflow` scope to the token and then re-run the workflow. This should resolve the issue.

**Comment by grulja** [comment]
> Please add `workflow` scope to the token and then re-run the workflow. This should resolve the issue.

`workflow` adds complete access to the repo, not sure we want to do that.

**Comment by grulja** [comment]
Last time I updated the [fork](https://github.com/FedoraQt/winget-pkgs) to make it work. Trying it now.

**Comment by grulja** [comment]
That worked. Sorry for noise.

PR opened: https://github.com/microsoft/winget-pkgs/pull/248337
