### ISSUE TITLE
macOS: Immediately jumps to "finished"

### ISSUE THREAD

**Issue by jlnr** [FedoraQt/MediaWriter#71]
A bug that I've experienced a few times is I can choose a USB stick, tap the button to write to the USB stick, and then MediaWriter immediately says it is "Finished". However, at this point nothing has been written.

If I then go through the process again, writing takes a few minutes, and everything works. But it's still a little confusing.

**Comment by MartinBriza** [comment]
Hello,
sorry about this problem. I'm releasing a new version in the nearest days where this kind of issues should be fixed. If something goes wrong, it should at least spit out an error message about it and there's even a debug mode which creates a log of events so I can see a bit more details about what happened.

**Comment by MartinBriza** [comment]
Please try downloading this release: https://github.com/MartinBriza/MediaWriter/releases/tag/4.0.95 and check if it still has the problem you reported.

**Comment by jlnr** [comment]
I could still reproduce the issue with 4.0.95 - I tried writing the F25 Workstation ISO and all it did was unmount the USB stick, then it jumped to "Finished". No error message, no log file that I can see.

The .app is also still unsigned and required the right-click->Open dance (contrary to the GitHub release notes, but unrelated to this issue).

**Comment by MartinBriza** [comment]
The log should be located in your Documents folder. Thanks for checking the signing.

**Comment by jlnr** [comment]
The localisation is also incomplete on my German macOS system (I guess it's up to me to send a PR now :P):

![before](https://cloud.githubusercontent.com/assets/70772/24203246/7ceb9cf2-0f15-11e7-828e-64eb7957566b.png)
![after](https://cloud.githubusercontent.com/assets/70772/24203247/7d0db274-0f15-11e7-80c9-f57fc144aa31.png)

**Comment by jlnr** [comment]
Log file:
[FedoraMediaWriter.log.txt](https://github.com/MartinBriza/MediaWriter/files/861756/FedoraMediaWriter.log.txt)

**Comment by MartinBriza** [comment]
Translations are done in Zanata, so no PRs required. :)

**Comment by MartinBriza** [comment]
Thanks for the log, I'll see what I can do about it. I think there's enough information to try something.

**Comment by MartinBriza** [comment]
So every time you try to write to your flash drive, it doesn't work on the first try but on the second, it always works?
Also regarding the signing: Do you have the strict policy enabled? Gatekeeper complains on my system but lets me start the application so I don't have to do the right click dance.

**Comment by jlnr** [comment]
Signing: Strange, I've downloaded FedoraMediaWriter-osx-4.0.95.dmg again and it seems to be signed now. I still have a screenshot from my last attempt in my rubbish bin:

![signing](https://cloud.githubusercontent.com/assets/70772/24378251/8b7dce44-1342-11e7-8e0a-6934855fa4b1.png)

Maybe a caching issue?

**Comment by jlnr** [comment]
Re: Writing, I am not sure if the issue is limited to Fedora Media Writer? Today I've decided to format my USB stick using Apple's Disk Utility, and the first attempt failed (couldn't unmount I think?), only the second attempt succeeded.

Anyway, I've started FMW and tried writing to the empty stick. After the admin password prompt, it immediately jumped to "Finished" without writing anything. cmd+Q, restart the app, this time the first attempt actually does something. Cancelled, restarted FMW, and again it worked on the first attempt.

Unplugged the USB stick, plugged it back in, works on the first attempt.

So maybe every action with this particular USB stick requires me retrying once? I'll see if I can find a second USB stick.

**Comment by jlnr** [comment]
Umm.... I've now copied Fedora to my 128GB SD card instead of my USB stick (disk2 instead of disk3)...ouch! I've attached the FMW log again, but I think it's impossible to tell from the log if this was a user error or a bug. I hope I have good backups :)

**Comment by MartinBriza** [comment]
The signing problem is strange but I'm glad to read it works fine now.

Regarding the writing, I'm really not sure what could be the culprit. I'll try formatting my flash drives on a different system and maybe rebooting before doing anything about them.
Btw it's worth noting mounts and dismounts are blocked while FMW is running to prevent the system from touching the drives during and after writing to them.

**Comment by jlnr** [comment]
I've tried the same process with another USB stick (a crappy/buggy USB 2 stick) and it worked right away. It's probably not worth pursuing this until someone else experiences the same problem.

A simple workaround could be to show an error message if the writing process succeeds after <2s, but that is a bit of a hack.

(And I think what happened when I accidentally copied Fedora to my SD card is that I plugged in the thumb drive while FMW was already running. The drive selection dropdown then shows both my SD card and my USB 3 stick, but defaults to the SD card - usually it defaults to the thumb drive.)

**Comment by MartinBriza** [comment]
Hmm, I'll try to find a less hacky solution to that.
Regarding the switching after you have plugged in an other drive, I don't think that should ever happen (even though that's something all programmers will tell you about their code). I'll see if about that too.

**Comment by cesarandreu** [comment]
Likely related, also on macOS. I tried using Fedora Media Writer v4.0.8 with my 32GB USB, but it seems to have ended up screwing up my 4TB external drive. When I tried booting up the USB drive, it failed to pass the initial health check.

Now `diskutil list` shows the following for the external HDD:

```
/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *4.0 TB     disk2
   1:                        EFI EFI                     209.7 MB   disk2s1
   2:          Apple_CoreStorage Two                     4.0 TB     disk2s2
   3:                 Apple_Boot Boot OS X               134.2 MB   disk2s3

/dev/disk3 (external, virtual):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     Apple_partition_scheme                        +4.0 TB     disk3
   1:        Apple_partition_map                         8.2 KB     disk3s1
   2:                  Apple_HFS                         5.4 MB     disk3s2
   3:                  Apple_HFS ANACONDA                12.0 MB    disk3s3
```

Found the following in system.log:

```
Apr  5 03:13:55 Odin Fedora Media Writer[59139]: BUG in libdispatch client: kevent[EVFILT_MACHPORT] monitored resource vanished before the source cancel handler was invoked
```

No log file was saved in my Documents folder.

**Comment by MartinBriza** [comment]
Log files are a thing of the new-ish versions (>4.0.95 and some 4.0.8-$number-$commit) so there's probably nothing.
Regarding your external drive, I'm sorry about that but FMW just writes to whatever you have selected. If you now have a Fedora live system on your external drive, you had selected that, unfortunately.

**Comment by jlnr** [comment]
Maybe a warning when selecting a device with >64 GB would make this all a little safer, most people are probably using USB thumb drives smaller than that.

**Comment by MartinBriza** [comment]
Yeah. Initially it didn't list external hard drives, however some flash
drive manufacturers decide to not mark their flash drives properly and they
act like extenal HDDs. I'll probably add some realistic heuristic or just
warn about those drives. Thanks for the suggestion.

2017-04-07 8:58 GMT+02:00 Julian Raschke <notifications@github.com>:

**Comment by grulja** [comment]
I believe this is no longer an issue since we changed the way how writing is done now on MacOS. Feel free to re-open if the issue is still reproducible with latest version.
